name: Tests
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run: yarn --immutable

      - name: ESLint
        run: yarn lint --cache-dir=".turbo"

      - name: Tests
        run: yarn test --cache-dir=".turbo"

      - name: Build
        run: yarn build --cache-dir=".turbo"
